import React from 'react';

const ReportGenerator = ({ analysisData, user }) => {
 if (!analysisData) return null;

 const handlePrint = () => {
 window.print();
 };

 return (
 <div className="bg-card dark:bg-dark-card p-8 rounded-lg shadow-md max-w-4xl mx-auto my-8 border border-border dark:border-dark-border print:bg-white dark:bg-gray-900 dark:border-gray-700 print:text-black print:shadow-none print:m-0 print:p-0 transition-colors duration-300">
 <div className="flex justify-between items-center border-b border-border dark:border-dark-border pb-4 mb-6 print:hidden">
 <h2 className="text-2xl font-bold text-text dark:text-dark-text">Forensic Analysis Report</h2>
 <button
 onClick={handlePrint}
 className="bg-primary text-white px-4 py-2 rounded shadow hover:bg-primary-hover transition"
 >
 Print Report
 </button>
 </div>

 <div className="print-area font-sans text-text dark:text-dark-text print:text-black">
 <div className="text-center mb-8 border-b-2 border-border dark:border-dark-border print:border-black pb-4">
 <h1 className="text-3xl font-bold uppercase tracking-wider">Official Forensic Report</h1>
 <p className="text-sm text-muted dark:text-dark-muted mt-1">Generated by Advanced Weapon Detection System</p>
 </div>

 <div className="grid grid-cols-2 gap-8 mb-8">
 <div>
 <h3 className="text-lg font-semibold border-b border-border dark:border-dark-border print:border-black pb-1 mb-3">Analysis Information</h3>
 <p><strong>Record ID:</strong> {analysisData.record_id}</p>
 <p><strong>Date & Time:</strong> {new Date().toLocaleString()}</p>
 <p><strong>Analyzed Image:</strong> {analysisData.filename}</p>
 </div>
 <div>
 <h3 className="text-lg font-semibold border-b border-border dark:border-dark-border print:border-black pb-1 mb-3">Analyst Information</h3>
 <p><strong>Name:</strong> {user?.name || user?.username || 'Unknown'}</p>
 <p><strong>Role:</strong> <span className="capitalize">{user?.role?.replace('_', ' ') || 'Analyst'}</span></p>
 </div>
 </div>

 <div className="bg-secondary dark:bg-dark-secondary p-6 rounded-lg border border-border dark:border-dark-border print:bg-white dark:bg-gray-900 dark:border-gray-700 print:border-black mb-8 transition-colors duration-300">
 <h3 className="text-xl font-bold mb-4">Detection Results</h3>
 <div className="grid grid-cols-2 gap-4">
 <div>
 <p className="text-sm text-muted dark:text-dark-muted uppercase">Predicted Weapon</p>
 <p className="text-lg font-semibold text-text dark:text-dark-text">{analysisData.weapon}</p>
 <p className="text-sm text-muted dark:text-dark-muted">Confidence: {(analysisData.weapon_probability * 100).toFixed(1)}%</p>
 </div>
 <div>
 <p className="text-sm text-muted dark:text-dark-muted uppercase">Predicted Wound Type</p>
 <p className="text-lg font-semibold text-text dark:text-dark-text">{analysisData.wound_type}</p>
 <p className="text-sm text-muted dark:text-dark-muted">Confidence: {(analysisData.wound_probability * 100).toFixed(1)}%</p>
 </div>
 </div>
 <div className="mt-4 pt-4 border-t border-border dark:border-dark-border print:border-black">
 <p className="text-sm text-muted dark:text-dark-muted uppercase">Severity Level</p>
 <p className={`text-lg font-bold ${analysisData.severity === 'Critical' || analysisData.severity === 'Severe'
 ? 'text-red-600' : 'text-yellow-600'
 }`}>{analysisData.severity}</p>
 </div>
 </div>

 <div className="mb-8">
 <h3 className="text-xl font-bold mb-3 border-b border-gray-800 print:border-black pb-2">Forensic Notes</h3>
 <ul className="list-disc pl-5 space-y-2">
 {analysisData.forensic_notes?.map((note, index) => (
 <li key={index}>{note}</li>
 ))}
 </ul>
 </div>

 <div className="mb-12">
 <h3 className="text-xl font-bold mb-3 border-b border-gray-800 print:border-black pb-2 text-red-600">Critical Precautions</h3>
 <ul className="list-disc pl-5 space-y-2 text-red-400 print:text-black">
 {analysisData.precautions?.map((precaution, index) => (
 <li key={index}>{precaution}</li>
 ))}
 </ul>
 </div>

 <div className="mt-16 pt-8 border-t-2 border-dashed border-gray-700 print:border-black flex justify-between">
 <div className="text-center w-64">
 <div className="border-b border-gray-800 print:border-black h-8 mb-2"></div>
 <p className="text-sm uppercase tracking-wide">Analyst Signature</p>
 </div>
 <div className="text-center w-64">
 <div className="border-b border-gray-800 print:border-black h-8 mb-2"></div>
 <p className="text-sm uppercase tracking-wide">Reviewer Signature</p>
 </div>
 </div>

 <div className="text-center mt-8 text-xs text-muted print:fixed print:bottom-4 print:w-full">
 <p>Confidential Medical and Forensic Data - Do not distribute without authorization.</p>
 </div>
 </div>
 </div>
 );
};

export default ReportGenerator;
